Array.prototype.indexOf||(Array.prototype.indexOf=function(b,c){if(null==this)throw new TypeError("Array.prototype.indexOf() - can't convert `"+this+"` to object");var a=isFinite(c)?Math.floor(c):0,d=this instanceof Object?this:Object(this),r=isFinite(d.length)?Math.floor(d.length):0;if(a>=r)return-1;0>a&&(a=Math.max(r+a,0));if(void 0===b){do if(a in d&&void 0===d[a])return a;while(++a<r)}else{do if(d[a]===b)return a;while(++a<r)}return-1});
function getCookie(b){b+="=";for(var c=decodeURIComponent(document.cookie).split(";"),a=0;a<c.length;a++){for(var d=c[a];" "===d.charAt(0);)d=d.substring(1);if(0===d.indexOf(b))return d.substring(b.length,d.length)}return""}
function submitName(){nametag=document.getElementById("name").value;var b=getCookie("usernames")||"[]";console.log(b);b=JSON.parse(b);-1!=b.indexOf(nametag)?alert("Back for more, "+b[b.indexOf(nametag)]+"?"):""!=nametag&&null!=nametag&&(b.push(nametag),setCookie("usernames",JSON.stringify(b),365))}function setCookie(b,c,a){var d=new Date;d.setTime(d.getTime()+864E5*a);a="expires="+d.toUTCString();document.cookie=b+"="+c+";"+a+";path=/"}
var run=!0,playGame=function(){function b(a,b){a=Math.ceil(a);b=Math.floor(b);return Math.floor(Math.random()*(b-a))+a}var c=document.querySelector("canvas"),a=c.getContext("2d"),d=0,r=!1,x=!1,y=!1,A=!1,n=0,l=3,e=c.width/2,f=c.height/2,B=250,p=40,t=1,C=b(90,c.width-30),D=b(90,c.height-30),F=0,h=.2*c.height,m=[],u=[];c.width=window.innerWidth;c.height=window.innerHeight;document.addEventListener("keydown",function(a){if((91===a.keyCode||17===a.keyCode)&&16===a.keyCode&&67===a.keyCode||123===a.keyCode)return!1;
    if(68===a.keyCode||39===a.keyCode)r=!0;else if(65===a.keyCode||37===a.keyCode)x=!0;else if(87===a.keyCode||38===a.keyCode)y=!0;else if(83===a.keyCode||40===a.keyCode)A=!0;80===a.keyCode&&(0===n?n+=1:1===n&&--n)},!1);document.addEventListener("keyup",function(a){if(68===a.keyCode||39===a.keyCode)r=!1;else if(65===a.keyCode||37===a.keyCode)x=!1;else if(87===a.keyCode||38===a.keyCode)y=!1;else if(83===a.keyCode||40===a.keyCode)A=!1},!1);var G=["#1f721f","#41763b","#57824b","#77a577","#3b774d"],E=function(a,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               b){this.x=a;this.y=b;this.color=G[Math.floor(Math.random()*G.length)]};E.prototype.makeEnemy=function(){a.beginPath();a.fillStyle=this.color;a.fillRect(this.x,this.y,h,h);0===n&&(this.x+=(e-this.x)/B,this.y+=(f-this.y)/B)};var v=0,H=15;v=0;var J=setInterval;0===n&&v++;J(void 0,10);setInterval(function(){0===n&&(F+=1,F===H&&(20>t?(t+=1,B*=.875,l+=.45,H+=15):t=20),a.font="20px Impact",a.fillStyle="blue",a.fillText("Level: "+t,50,80))},1E3);setInterval(function(){if(run){a.clearRect(0,0,innerWidth,innerHeight);
    a.font="20px Impact";a.fillStyle="red";a.fillText("Health: "+p,50,40);a.font="20px Impact";a.fillStyle="red";a.fillText("Score: "+d,50,60);a.font="20px Impact";a.fillStyle="red";a.fillText("Level: "+t,50,80);a.beginPath();a.fillStyle="orange";a.fillRect(e,f,30,30);a.font="15px Arial";0>f-50?0>e-10?(a.textAlign="left",a.fillText(nametag,e,f+60)):e+50>c.width?(a.textAlign="right",a.fillText(nametag,e+25,f+60)):0<e-10&&e+20<c.width&&(a.textAlign="center",a.fillText(nametag,e+15,f+60)):e+50>c.width?(a.textAlign=
        "right",a.fillText(nametag,e+25,f-30)):0>e-10?(a.textAlign="left",a.fillText(nametag,e,f-30)):(a.textAlign="center",a.fillText(nametag,e+15,f-30));a.textAlign="center";for(k=0;k<m.length;k++)m[k].makeEnemy();u=m;for(g=0;g<u.length;g++)Math.abs(m[g].x-e)<h&&Math.abs(m[g].y-f)<h&&m.splice(g,1);0<p&&(a.beginPath(),a.fillStyle="red",a.fillRect(e-5,f+40,p,10));a.beginPath();a.fillStyle="#e21638";a.fillRect(C,D+10,h,h);Math.abs(C-e)<h&&Math.abs(D-f)<h&&(40>p&&p++,d+=100,C=b(90,c.width-30),D=b(90,c.height-
        30),v+=1);0===n&&(x&&0<e-l&&(e-=l),r&&e+30+l<c.width&&(e+=l),y&&0<f-l&&(f-=l),A&&f+30+l<c.height&&(f+=l));for(z=0;z<u.length;z++)Math.abs(m[z].x-e)<h&&Math.abs(m[z].y-f)<h&&(p-=.5,m.shift());u=m;if(0>=p){showPage(2);console.log(currentPage);document.getElementById("score").innerHTML=d;var w=document.getElementById("end");console.log(w);jvnrvjjrvjrvjrvjrv=firebase.database().ref("scores");var I=d;0===n&&v++;I===NaN+100*v&&(d=jvnrvjjrvjrvjrvjrv.push({name:nametag,score:d}));firebase.database().ref("scores").once("value",
        function(a){data=[];for(var b in a.val())data.push(a.val()[b]);data=data.sort(function(a,b){return b.score-a.score});console.log(data);w.innerHTML="<tr><th>Position</th><th>Name</th><th>Score</th></tr>";for(b=0;5>b;b++)w.innerHTML+="<tr><td>"+(b+1)+"</td><td>"+data[b].name+"</td><td>"+data[b].score+"</td></tr>"});firebase.database().ref("plays").once("value",function(a){plays=a.val();firebase.database().ref("plays").set(plays+1)});run=!1}}},10);setInterval(function(){run&&(0===n&&d++,a.font="20px Impact",
    a.fillStyle="red",a.fillText("Score: "+d,50,60))},10);setInterval(function(){0===n&&40>p&&p++},5E3);setInterval(function(){if(0===n)for(var a=b(3,5),d=0;d<a+1;d++){for(var h=b(0,c.width),l=b(0,c.height);h>e-50&&h<e+50&&l>f-50&&l<e+50;)h=b(0,c.width),l=b(0,c.height);m.push(new E(h,l));u.push(new E(h,l))}},500);setInterval(function(){if(0===n)if(40<m.length)for(q=0;20>q;q++)m.shift();else for(q=0;4>q;q++)m.shift()},5E3)},pages=document.getElementsByClassName("page"),currentPage=0,showNextPage=function(){for(var b=
    0;b<pages.length;b++)pages[b].style.display="none";currentPage+=currentPage===pages.length?0:1;pages[currentPage].style.display="block"},showPage=function(b){for(var c=0;c<pages.length;c++)pages[c].style.display="none";pages[b].style.display="block";currentPage=b};function enterDown(b){13===b.keyCode&&0===currentPage&&""!=document.getElementById("name").value&&(submitName(),showNextPage(),playGame())}
firebase.database().ref("scores").once("value",function(b){data=[];for(var c in b.val())data.push(b.val()[c]);data=data.sort(function(a,b){return b.score-a.score});document.getElementById("lb").innerHTML="<tr><th>Position</th><th>Name</th><th>Score</th></tr>";for(c=0;5>c;c++)document.getElementById("lb").innerHTML+="<tr><td>"+(c+1)+"</td><td>"+data[c].name+"</td><td>"+data[c].score+"</td></tr>"});document.getElementById("leaderboard-button").addEventListener("click",function(){showPage(3)});
document.getElementById("back-button").addEventListener("click",function(){showPage(0)});document.addEventListener("keydown",enterDown,!1);


/*
So, hackers...
you thought it would be fun to put in your own scores on our leaderboard?
well...HAVE FUN DOING IT NOW!!!

MWAHAHAHAHAHAHA!!!!!

            -NITHIN VADAKKEN
 */